### ISSUE TITLE
Change project description to "button"

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/button_tracker#1]
Currently it says "mouse/button", but this library will focus on buttons.

**Comment by bvssvni** [comment]
@RCIX Is this right? Or does it include mouse buttons?

**Comment by bvssvni** [comment]
It includes all buttons. Closing.

**Comment by RinCamelia** [comment]
Yep, no discrimination. It's a bit odd, but unless there's a pressing desire to make a mouse_controller and regroup those buttons there, the plan is to leave it like this.
